export const AGENT_GOALS_DATA = [
    {
        key: 1,
        agents: 'John Doe',
        closed_deals: 10,
        upcoming_deals: 5,
        commission_earned: 1000,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
    {
        key: 2,
        agents: 'Jane Doe',
        closed_deals: 10,
        upcoming_deals: 5,
        commission_earned: 1000,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
    {
        key: 3,
        agents: 'Alex Smith',
        closed_deals: 7,
        upcoming_deals: 3,
        commission_earned: 750,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
    {
        key: 4,
        agents: 'Maria Garcia',
        closed_deals: 12,
        upcoming_deals: 6,
        commission_earned: 1200,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
    {
        key: 5,
        agents: 'David Lee',
        closed_deals: 8,
        upcoming_deals: 4,
        commission_earned: 900,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
    {
        key: 6,
        agents: 'Emily Chen',
        closed_deals: 9,
        upcoming_deals: 2,
        commission_earned: 850,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
    {
        key: 7,
        agents: 'Michael Brown',
        closed_deals: 11,
        upcoming_deals: 7,
        commission_earned: 1300,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
    {
        key: 8,
        agents: 'Olivia Wilson',
        closed_deals: 6,
        upcoming_deals: 3,
        commission_earned: 700,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
    {
        key: 9,
        agents: 'Liam Martinez',
        closed_deals: 13,
        upcoming_deals: 8,
        commission_earned: 1400,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
    {
        key: 10,
        agents: 'Sophia Anderson',
        closed_deals: 5,
        upcoming_deals: 2,
        commission_earned: 600,
        commission_goal: 'Set Goals',
        goal_progress: '',
    },
] as const;

export const AGENT_GOAL_SELECT_OPTIONS = [
    { value: '1', label: 'Commission Goal 1' },
    { value: '2', label: 'Commission Goal 2' },
    { value: '3', label: 'Commission Goal 3' },
] as const;


